# Generated by Django 3.0 on 2021-10-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrfoessionDocument',
            fields=[
                ('areaNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('plannedNumber', models.IntegerField(unique=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('apartmentNumber', models.IntegerField(blank=True, null=True)),
                ('apartmentArea', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
