# Generated by Django 3.0 on 2021-10-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionDocument',
            fields=[
                ('areaNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('plannedNumber', models.IntegerField(unique=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('apartmentNumber', models.IntegerField(blank=True, null=True)),
                ('apartmentArea', models.IntegerField(blank=True, null=True)),
                ('professionNumber', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PrfoessionDocument',
        ),
    ]
