# Generated by Django 3.0 on 2021-10-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20211008_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionNumber', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='professiondocument',
            name='date',
        ),
        migrations.RemoveField(
            model_name='professiondocument',
            name='professionNumber',
        ),
        migrations.AddField(
            model_name='professiondocument',
            name='proof',
            field=models.ManyToManyField(to='documents.ProfessionProof'),
        ),
    ]
