# Generated by Django 3.0 on 2021-10-09 22:43

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_constructionfloor_constructionlicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'ممتازة'), (2, 'جيده'), (3, 'سيئة')], null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=documents.models.get_image_filename, verbose_name='Image')),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='documents.Location')),
            ],
        ),
    ]
