# Generated by Django 3.0 on 2021-10-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_location_locationimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='finishing',
            field=models.SmallIntegerField(choices=[(1, 'دهانات'), (2, 'هيكل إنشائى'), (3, 'الأرضيات')], null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='zone_level',
            field=models.SmallIntegerField(choices=[(1, 'مرتفع'), (2, 'منخفض')], null=True),
        ),
    ]
